# Generated by Django 3.0.6 on 2020-06-05 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=2)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=128)),
                ('mobile', models.IntegerField(max_length=128)),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(max_length=128)),
                ('address3', models.CharField(max_length=128)),
                ('address4', models.CharField(max_length=128)),
                ('zip_code', models.IntegerField(max_length=128)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=128)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
