# Generated by Django 3.0.6 on 2020-06-05 23:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ref_payment_methods',
            fields=[
                ('payment_method_code', models.IntegerField(primary_key=True, serialize=False)),
                ('payment_method_des', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Ref_payment_methods',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('gender', models.CharField(max_length=2)),
                ('dob', models.DateField()),
                ('email', models.CharField(max_length=128)),
                ('mobile', models.IntegerField()),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(max_length=128)),
                ('address3', models.CharField(max_length=128)),
                ('address4', models.CharField(max_length=128)),
                ('zip_code', models.IntegerField()),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=128)),
                ('create_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('country', models.CharField(max_length=128)),
                ('auth_user_id', models.OneToOneField(db_column='auth_user_id', on_delete=django.db.models.deletion.DO_NOTHING, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Customers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='cust_payments_methods',
            fields=[
                ('cust_payment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_number', models.CharField(max_length=24)),
                ('name_on_card', models.CharField(max_length=256)),
                ('expiry_date', models.DateField()),
                ('other_details', models.CharField(max_length=256)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.Customers')),
                ('payment_method_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.ref_payment_methods')),
            ],
            options={
                'db_table': 'Cust_Payments_Methods',
                'managed': True,
            },
        ),
    ]
